# Generated by Django 3.1.6 on 2021-02-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapi', '0002_bills_billsproducts_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillsProducts',
        ),
    ]
